### ISSUE TITLE
[Bug] AI container problem

### ISSUE THREAD

**Issue by fractalshine** [AppFlowy-IO/AppFlowy-Cloud#1072]
**Describe the bug**
AI crashing all the time

**To Reproduce**
Just run with docker compose up -d

**Expected behavior**
Working AI

**Desktop (please complete the following information):**
Ddebian 12, latest docker

**Additional context**
Nginx reverse proxy

```
server {
    listen 80;
    server_name appflowy.mydomain.com;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name appflowy.mydomain.com;

    ssl_certificate /etc/letsencrypt/live/appflowy.mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/appflowy.mydomain.com/privkey.pem;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://localhost:8585;
        proxy_redirect off;
        proxy_http_version 1.1;
        client_max_body_size 0;
    }


}
```
Container log

```
ai-1  | The above exception was the direct cause of the following exception:
ai-1  |
ai-1  | Traceback (most recent call last):
ai-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
ai-1  |     sys.exit(main())
ai-1  |              ^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
ai-1  |     return self.main(*args, **kwargs)
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
ai-1  |     rv = self.invoke(ctx)
ai-1  |          ^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
ai-1  |     return ctx.invoke(self.callback, **ctx.params)
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
ai-1  |     return __callback(*args, **kwargs)
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 410, in main
ai-1  |     run(
ai-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 577, in run
ai-1  |     server.run()
ai-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
ai-1  |     return asyncio.run(self.serve(sockets=sockets))
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
ai-1  |     return runner.run(main)
ai-1  |            ^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
ai-1  |     return self._loop.run_until_complete(task)
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
ai-1  |     return future.result()
ai-1  |            ^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
ai-1  |     await self._serve(sockets)
ai-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
ai-1  |     config.load()
ai-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
ai-1  |     self.loaded_app = import_from_string(self.app)
ai-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
ai-1  |     module = importlib.import_module(module_str)
ai-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
ai-1  |     return _bootstrap._gcd_import(name[level:], package, level)
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
ai-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
ai-1  |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
ai-1  |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
ai-1  |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
ai-1  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
ai-1  |   File "/usr/src/app/server/main.py", line 11, in <module>
ai-1  |     from app import create_app
ai-1  |   File "/usr/src/app/server/app/__init__.py", line 9, in <module>
ai-1  |     from server.app.router.desktop_app import s3_router
ai-1  |   File "/usr/src/app/server/app/__init__.py", line 26, in <module>
ai-1  |     from server.app.postgres.chat_persistence import PgChatPersistence
ai-1  |   File "/usr/src/app/server/app/postgres/chat_persistence.py", line 14, in <module>
ai-1  |     from server.app.postgres.sql import SummaryChatMessage
ai-1  |   File "/usr/src/app/server/app/postgres/sql.py", line 27, in <module>
ai-1  |     SQLModel.metadata.create_all(engine)
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/schema.py", line 5868, in create_all
ai-1  |     bind._run_ddl_visitor(
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3252, in _run_ddl_visitor
ai-1  |     with self.begin() as conn:
ai-1  |          ^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
ai-1  |     return next(self.gen)
ai-1  |            ^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3242, in begin
ai-1  |     with self.connect() as conn:
ai-1  |          ^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
ai-1  |     return self._connection_cls(self)
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
ai-1  |     Connection._handle_dbapi_exception_noconnection(
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2442, in _handle_dbapi_exception_noconnection
ai-1  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
ai-1  |     self._dbapi_connection = engine.raw_connection()
ai-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
ai-1  |     return self.pool.connect()
ai-1  |            ^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
ai-1  |     return _ConnectionFairy._checkout(self)
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
ai-1  |     fairy = _ConnectionRecord.checkout(pool)
ai-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
ai-1  |     rec = pool._do_get()
ai-1  |           ^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
ai-1  |     with util.safe_reraise():
ai-1  |          ^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
ai-1  |     raise exc_value.with_traceback(exc_tb)
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
ai-1  |     return self._create_connection()
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
ai-1  |     return _ConnectionRecord(self)
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
ai-1  |     self.__connect()
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
ai-1  |     with util.safe_reraise():
ai-1  |          ^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
ai-1  |     raise exc_value.with_traceback(exc_tb)
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
ai-1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
ai-1  |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
ai-1  |     return dialect.connect(*cargs, **cparams)
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 621, in connect
ai-1  |     return self.loaded_dbapi.connect(*cargs, **cparams)
ai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 98, in connect
ai-1  |     attempts = conninfo_attempts(params)
ai-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
ai-1  |   File "/usr/local/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts
ai-1  |     raise e.OperationalError(str(last_exc))
ai-1  | sqlalchemy.exc.OperationalError: (psycopg.OperationalError) [Errno -2] Name or service not known
ai-1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by khorshuheng** [comment]
Seems like the AI service can't reach the postgres service. Can you check if:
1. Postgres service is running without crash (if you are using postgres within docker compose)
2. APPFLOWY_AI_DATABASE_URL is set correctly and reachable from AI service

**Comment by fractalshine** [comment]
Yep, postgres running w/o any error, appflowy works well. Didn't change ai url, using stock config from git repo:
`APPFLOWY_AI_DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}`

**Comment by fractalshine** [comment]
That's it. Some characters in password were not transferred properly, probably @ symbol
