### ISSUE TITLE
[Bug] appflowy not work with authentik

### ISSUE THREAD

**Issue by anschein** [AppFlowy-IO/AppFlowy-Cloud#1096]
I'm trying to use authentik as a saml provider, authentik is a third party open source authentication system that works well with my other services, I also checked the saml output endpoints of authentik and it is able to generate the xml metadata correctly, but I'm populating the metadata address into appflowy The following error is thrown when adding the saml provider:

2024-12-21T04:17:40Z INF component=api error=400: HTTP 406 error fetching SAML Metadata from URL 'https://example.com/api/v3/providers/saml/8/ metadata/' method=POST msg=400: HTTP 406 error fetching SAML Metadata from URL 'https://example.com/api/v3/providers/saml/8/metadata/' path=/ admin/sso/providers referer=appflowy-flutter:// remote_addr=172.30.0.10 request_id=ad452403-acaf-48f0-9897-962aa9343cbd

The xml output of the authentik endpoint is as follows:

{"metadata":"<md:EntityDescriptor xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\" xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\" xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\" xmlns:md=\"urn:oasis:names:tc:SAML:2.0:metadata\" xmlns:xenc=\"http://www.w3.org/2001/04/xmlenc#\" ID=\"_19222da8cefbc5daf734bef3c753f512a48a21b0581f1dd6778fa7dd43e1d57d\" entityID=\"authentik\"><md:IDPSSODescriptor protocolSupportEnumeration=\"urn:oasis:names:tc:SAML:2.0:protocol\"><md:SingleLogoutService Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect\" Location=\"https://example.com/application/saml/appflowy/slo/binding/redirect/\"/><md:SingleLogoutService Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST\" Location=\"https://example.com/application/saml/appflowy/slo/binding/post/\"/><md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat><md:SingleSignOnService Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect\" Location=\"https://example.com/application/saml/appflowy/sso/binding/redirect/\"/><md:SingleSignOnService Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST\" Location=\"https://example.com/application/saml/appflowy/sso/binding/post/\"/></md:IDPSSODescriptor></md:EntityDescriptor>"}

**Comment by khorshuheng** [comment]
We are using Supabase Auth to handle the SAML 2.0 flow. When adding a new SSO provider, the following function is called:
https://github.com/supabase/auth/blob/v2.159.1/internal/api/ssoadmin.go#L176

It is assumed that the response is in xml format, as opposed to json format.

I have looked through the documentation for Authentik endpoints, but i have not been able to find an endpoint that returns the metadata as xml as opposed to json.

**Comment by khorshuheng** [comment]
I have reproduced the issue using a minimal golang application:
```
package main

import (
	"fmt"
	"io"
	"net/http"
)

func main() {
	fmt.Println("Sending requests")
	url := "https://<authentik url>/api/v3/providers/saml/1/metadata/?download=true"
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		panic(err)
	}

	req.Header.Set("Accept", "application/xml;charset=UTF-8")
	req.Header.Set("Accept-Charset", "UTF-8")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(data))
}

```

Seems like this is due to req.Header.Set("Accept-Charset", "UTF-8")

**Comment by khorshuheng** [comment]
After looking through Authentik source code, this is my hypothesis:

Authentik uses Django framework. By default, Django framework has the following rederer:
```
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]
}
```
When an `Accept` header is passed from the client, such as what happens here in Supabase Auth, Django will check the renderer classes to see if it is supported. Unfortunately, Django doesn't support XML by default, a plugin is required to add the support. From my preliminary investigation it doesn't appear that Authentik uses this plugin.

Therefore, the response 406 is returned, because there's no renderer class that can handle the xml accept handle.

Ironically, if the caller doesn't include the `Accept` handler, Authentik does provide the response with content type = "application/xml" .

It is possible to reproduce this issue via curl:
`curl -v "http://localhost:9080/api/v3/providers/saml/1/metadata/?download" -H "Accept: application/xml"`
vs
`curl -v "http://localhost:9080/api/v3/providers/saml/1/metadata/?download"`

**Comment by khorshuheng** [comment]
I have also raised an issue here: https://github.com/goauthentik/authentik/issues/12483 .

**Comment by anschein** [comment]
Thank you very much for your enthusiastic support, at the moment it looks like the only way to make authentik work in conjunction with appflowy cloud is to wait for authentik to fix the issue, hopefully it won't be too long a wait, in my environment there are about 5-10 people using my home server, and to be able to add appflowy I'm sure would be a big step forward for me

**Comment by khorshuheng** [comment]
Actually, there is another way. If you have some experience in Golang and building docker image, you can simply modify the gotrue code base such that the "Accept" header is not sent, then build a new image. You will also need to update the metadata URL from /metadata to /metadata/?download

**Comment by Rynoxx** [comment]
A bugfix for this has been merged in Authentik, should be included in the next release.  
Unsure when the next release is.

goauthentik/authentik#12518

**Comment by khorshuheng** [comment]
@Rynoxx Thank you. On our end, we will also need to add some fix to the docker compose, such that the API external URL includes the /gotrue suffix. I will fix it both in this repository, and also the unofficial helm chart.

**Comment by alex2702** [comment]
Hey, can I ask how you've configured AppFlowy and GoTrue to (almost) work with Authentik? I'm trying to do the same but after initiating a login through Authentik, I'm getting a 404 on `/gotrue/sso/saml/acs`.

The response body says:
```json
{"code":404,"error_code":"saml_provider_disabled","msg":"SAML 2.0 is disabled"}
```

I've set the following environment variables for my GoTrue container:
```sh
GOTRUE_EXTERNAL_SAML_ENABLED=true
GOTRUE_EXTERNAL_SAML_METADATA_URL="https://{my_authentik_host}/application/saml/appflowy/metadata/"
GOTRUE_EXTERNAL_SAML_API_BASE=http://127.0.0.1:9999
GOTRUE_EXTERNAL_SAML_NAME=Authentik
```

I've also created an SSO entry in the AppFlowy Admin console.

**Comment by Rynoxx** [comment]
@alex2702 I believe the thing you're missing is `GOTRUE_SAML_PRIVATE_KEY`

I found it from a guide here: https://calvincchan.com/blog/self-hosted-supabase-enable-sso

The only things I have configured for SAML are 
```
GOTRUE_DISABLE_SIGNUP=false
GOTRUE_SAML_ENABLED=true
GOTRUE_SAML_PRIVATE_KEY=<the generated-key in a single line>
```

Annoyingly it seems like signup has to be enabled for creating the accounts, but after the accounts have been created you can disable signup.
After that, it worked for me initiating the sign-in flow from Authentik.

I had to do a little bit of finicky stuff in authentik to get that to work as well. But I believe that might be due to how things are set up in the kubernetes helm chart, so might not be 100% relevant for a docker-setup.
I had to set the ACS URL, Issuer and Audience to include the port as well, i.e. `https://{my_appflowy_host}:443/gotrue/sso/saml/acs`

**Comment by alex2702** [comment]
Thanks @Rynoxx, that solved my problem! 😄 I did not have to include the ports (Podman-based setup).

One question, though: When I'm logged into the desktop app, going through Authentik just opens the app, as expected. When I'm not logged in, it also opens the app but I get the login form, need to enter my email address, and go through the magic link. I'm assuming that part shouldn't be needed with a proper SAML setup?

If anyone else gets a 405 as a GoTrue response: In the Authentik provider, I had to set `Service Provider Binding` to `Post`.

**Comment by khorshuheng** [comment]
@Rynoxx The need to appending the port is actually due to how the external URL is set. This can be avoided if I improve the helm chart such that, the port is only appended if it is non standard port.

**Comment by AshDevFr** [comment]
Right now it's working for me if I use the application because `GOTRUE_SITE_URL` is set to `appflowy-flutter://`.
But how to make SAML redirect to the webapp? If I set `GOTRUE_SITE_URL` to `https://appflowy.<domain>` it won't work.

I'll get `https://appflowy.<domain>/api/user/workspace 401 (Unauthorized)` and :

```
{
    "message": "Request failed with status code 401",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 401\n    at c1 (https://appflowy.<domain>/static/js/index-DtNaTpE1.js:251:1045)\n    at XMLHttpRequest.d (https://appflowy.<domain>/static/js/index-DtNaTpE1.js:251:5892)\n    at la.request (https://appflowy.<domain>/static/js/index-DtNaTpE1.js:253:1961)\n    at async qO (https://appflowy.<domain>/static/js/index-DtNaTpE1.js:256:84290)\n    at async Kr.getUserWorkspaceInfo (https://appflowy.<domain>/static/js/index-DtNaTpE1.js:256:105030)\n    at async https://appflowy.<domain>/static/js/app.hooks-CKotuDdw.js:9:29133",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http",
            "fetch"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json"
        },
        "baseURL": "",
        "method": "get",
        "url": "/api/user/workspace"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 401
}
```

**Comment by khorshuheng** [comment]
You can refer to: https://github.com/AppFlowy-IO/AppFlowy-Web/issues/19
